project:
  title: NEUROCOGNITIVE EXAMINATION
  output-dir: neuro_report
  # pre-render: prerender.R
  render:
    - Biggie.qmd

format:
  neurotyp-typst:
    keep-typ: true
    fontsize: 11pt
    papersize: us-letter
    number-sections: false

execute:
  warning: false
  echo: false
  message: false
  freeze: auto
  cache: true

editor:
  markdown:
    wrap: sentence
    canonical: true
fig-width: 6
fig-asp: 0.618
out-width: "70%"
fig-align: center
fig-format: svg
fig-dpi: 270
df-print: kable
reference-location: document
bibliography: refs.bib
