params:
  patient: Biggie
  first_name: Biggie
  last_name: Smalls
  dob: 1991-01-01
  doe1: 2023-07-01
  doe2: 2023-08-01
  doe3: 2023-09-01
  sex: female
  sex_cap: Female
  age: 12
  education: sixth grade
  handedness: right
  referral: self-referred
  observer: Mrs. Smalls
  observer_relation: mother
  he_she: she
  he_she_cap: She
  his_her: her
  his_her_cap: Her
  him_her: her
  him_her_cap: Her
  dx1: attention-deficit/hyperactivity disorder (ADHD)
  dx2: anxiety
  dx3: depression
